name: Günlük Token Güncelle

on:
  schedule:
    - cron: '0 2 * * *'  # UTC 02:00 (Türkiye’de ~05:00)
  workflow_dispatch:

jobs:
  update-token:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Python kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Token alma işlemi
        run: python get_token.py

      - name: token.txt dosyası varsa commit et
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add token.txt || true
          git commit -m "🔄 Token güncellendi" || echo "Token’da değişiklik yok"
          git push || echo "Push edilemedi"
