name: Fetch Token

on:
  schedule:
    - cron: '0 */24 * * *'
  workflow_dispatch:

jobs:
  fetch-token:
    runs-on: ubuntu-latest

    steps:
      - name: Repo'yu klonla
        uses: actions/checkout@v3

      - name: Python kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: requests modülünü yükle
        run: pip install requests

      - name: Token dosyasını oluştur
        run: python get_token.py

      - name: Git ayarları ve push
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          if [ -f "stream_token.txt" ]; then
            git add stream_token.txt
            git diff --cached --quiet || (
              git commit -m "Otomatik token güncellemesi [skip ci]"
              git push
            )
          else
            echo "stream_token.txt dosyası yok, push yapılmayacak."
