name: Token Fetch

on:
  schedule:
    - cron: '0 */24 * * *'
  workflow_dispatch:

jobs:
  update-token:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Token Script
        run: python get_token.py

      - name: Commit and Push if Changed
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          if [ -f stream_token.txt ]; then
            git add stream_token.txt
            git diff --cached --quiet || (
              git commit -m "Auto-update token [skip ci]"
              git push
            )
          fi
