name: Token Updater

on:
  schedule:
    - cron: '0 2 * * *'  # Her gün UTC 02:00'de çalışacak
  workflow_dispatch:     # Elle tetiklemek için

jobs:
  update-token:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests

    - name: Run get_token.py script
      run: python get_token.py
